name: GrillaFux
options:
  bundleIdPrefix: com.basquetpass
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
targets:
  GrillaFux:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [GrillaFux]
    info:
      path: GrillaFux/Info.plist
      properties:
        CFBundleDisplayName: Grilla Fux
        UILaunchStoryboardName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseMessaging
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.basquetpass.logistica
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ZY8K4XH28N
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: "GrillaFux Distribution"
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
