name: GrillaFux

# 🔥 Post-Generation Hook: Resolve dependencies immediately
postGenCommand: |
  xcodebuild -resolvePackageDependencies -project GrillaFux.xcodeproj -scheme GrillaFux
options:
  bundleIdPrefix: com.basquetpass
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.28.1
# Configuración a nivel de PROYECTO (Desactivamos firma para dependencias/SPM)
settings:
  base:
    # Relaxed signing for Project level - let defaults apply
    SWIFT_VERSION: 5.7
targets:
  GrillaFux:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [GrillaFux]
    info:
      path: GrillaFux/Info.plist
    entitlements:
      path: GrillaFux/GrillaFux.entitlements
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseMessaging
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.basquetpass.logistica
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ZY8K4XH28N
        CODE_SIGN_STYLE: Manual
        SWIFT_VERSION: 5.7
        CODE_SIGN_ENTITLEMENTS: GrillaFux/GrillaFux.entitlements
        PROVISIONING_PROFILE_SPECIFIER: "GrillaFux Distribution"
        # 🔑 Explicit signing for the app target
        CODE_SIGNING_ALLOWED: YES
        CODE_SIGNING_REQUIRED: YES
        CODE_SIGN_IDENTITY: "Apple Distribution"
